
spring:
  application:
    name: sums-admin-service
      
  datasource:
    url: jdbc:mysql://localhost:3306/SUMS_ADMIN_SERVICE
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    
server:
  port: 9000
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka
